### ISSUE TITLE
Console Errors When window.localStorage Unavailable (iFrame)

### ISSUE THREAD

**Issue by asennyey** [aws-observability/aws-rum-web#117]
I'm trying to use RUM in an iFrame which has no access to the window.localStorage value.

Environment:
Angular 10.21 in an iFrame (on the same domain)
RUM 1.2.1

I'm injecting the script into head dynamically with the following code,
```
loadRum() {
    (window as any).AwsRumClient = {
      q: [],
      n: 'cwr',
      i: environment.rum.cwrId,
      v: '1.0.0',
      r: 'us-west-2',
      c: {
        sessionSampleRate: 1,
        guestRoleArn: environment.rum.guestRoleArn,
        identityPoolId: environment.rum.identityPoolId,
        endpoint: 'https://dataplane.rum.us-west-2.amazonaws.com',
        telemetries: ['performance', 'errors', 'http'],
        allowCookies: true,
        enableXRay: false,
        cookieAttributes: {
          domain: window.location.hostname,
          path: '/',
          sameSite: 'None',
          secure: true,
        },
      },
    };
    const x = (window as any).AwsRumClient;
    (window as any).cwr = (a, p) => {
      x.q.push({ a, p });
    };
    const z = document.createElement('script');
    z.async = true;
    z.src = 'https://client.rum.us-east-1.amazonaws.com/1.2.1/cwr.js';
    document.head.insertBefore(z, document.getElementsByTagName('script')[0]);
  }
```

Is it possible to add support for storing authentication tokens in cookies when localStorage is not supported (ie in an iFrame)? This doesn't affect usability of RUM, but it does lead to a series of console errors, since the reject in https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/Authentication.ts#L71 is not caught.

The affected lines are 
- https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/Authentication.ts#L86
- https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/Authentication.ts#L131 

```
polyfills.cf07b70d8bd3c7d2eb81.js:1 Error: Uncaught (in promise): [object Undefined]
    at Z (polyfills.cf07b70d8bd3c7d2eb81.js:1:12260)
    at polyfills.cf07b70d8bd3c7d2eb81.js:1:11343
    at cwr.js:formatted:1941:44
    at new O (polyfills.cf07b70d8bd3c7d2eb81.js:1:14095)
    at e.<anonymous> (cwr.js:formatted:1939:40)
    at cwr.js:formatted:1905:39
    at Object.next (cwr.js:formatted:1918:22)
    at cwr.js:formatted:1823:45
    at new O (polyfills.cf07b70d8bd3c7d2eb81.js:1:14095)
    at _ (cwr.js:formatted:1800:20)
n.onUnhandledError @ polyfills.cf07b70d8bd3c7d2eb81.js:1
polyfills.cf07b70d8bd3c7d2eb81.js:1 Error: Uncaught (in promise): [object Undefined]
    at Z (polyfills.cf07b70d8bd3c7d2eb81.js:1:12260)
    at Z (polyfills.cf07b70d8bd3c7d2eb81.js:1:11791)
    at polyfills.cf07b70d8bd3c7d2eb81.js:1:11343
    at c (cwr.js:formatted:1817:30)
    at cwr.js:formatted:1823:17
    at new O (polyfills.cf07b70d8bd3c7d2eb81.js:1:14095)
    at _ (cwr.js:formatted:1800:20)
    at e.AnonymousCredentialsProvider (cwr.js:formatted:1936:28)
    at e.<anonymous> (cwr.js:formatted:1928:45)
    at cwr.js:formatted:1905:39
n.onUnhandledError @ polyfills.cf07b70d8bd3c7d2eb81.js:1
2polyfills.cf07b70d8bd3c7d2eb81.js:1 Uncaught (in promise) undefined
invoke @ polyfills.cf07b70d8bd3c7d2eb81.js:1
run @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
c @ cwr.js:formatted:1817
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
AnonymousCredentialsProvider @ cwr.js:formatted:1936
(anonymous) @ cwr.js:formatted:1928
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
ChainAnonymousCredentialsProvider @ cwr.js:formatted:1926
e.setAwsCredentials @ cwr.js:formatted:4231
e.initDispatch @ cwr.js:formatted:5485
e @ cwr.js:formatted:5432
e.initCwr @ cwr.js:formatted:5927
(anonymous) @ cwr.js:formatted:5900
(anonymous) @ cwr.js:formatted:5838
(anonymous) @ cwr.js:formatted:5851
(anonymous) @ cwr.js:formatted:5756
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Rn @ cwr.js:formatted:5733
e.init @ cwr.js:formatted:5888
(anonymous) @ cwr.js:formatted:5945
(anonymous) @ cwr.js:formatted:5946
(anonymous) @ cwr.js:formatted:5947
2polyfills.cf07b70d8bd3c7d2eb81.js:1 Uncaught (in promise) undefined
invoke @ polyfills.cf07b70d8bd3c7d2eb81.js:1
run @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleMicroTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
P @ polyfills.cf07b70d8bd3c7d2eb81.js:1
then @ polyfills.cf07b70d8bd3c7d2eb81.js:1
catch @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ cwr.js:formatted:1928
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
ChainAnonymousCredentialsProvider @ cwr.js:formatted:1926
e.setAwsCredentials @ cwr.js:formatted:4231
e.initDispatch @ cwr.js:formatted:5485
e @ cwr.js:formatted:5432
e.initCwr @ cwr.js:formatted:5927
(anonymous) @ cwr.js:formatted:5900
(anonymous) @ cwr.js:formatted:5838
(anonymous) @ cwr.js:formatted:5851
(anonymous) @ cwr.js:formatted:5756
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Rn @ cwr.js:formatted:5733
e.init @ cwr.js:formatted:5888
(anonymous) @ cwr.js:formatted:5945
(anonymous) @ cwr.js:formatted:5946
(anonymous) @ cwr.js:formatted:5947
polyfills.cf07b70d8bd3c7d2eb81.js:1 Uncaught (in promise) undefined
invoke @ polyfills.cf07b70d8bd3c7d2eb81.js:1
run @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
c @ cwr.js:formatted:1817
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
AnonymousStorageCredentialsProvider @ cwr.js:formatted:1952
invoke @ polyfills.cf07b70d8bd3c7d2eb81.js:1
run @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ cwr.js:formatted:1941
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ cwr.js:formatted:1939
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
AnonymousCredentialsProvider @ cwr.js:formatted:1936
(anonymous) @ cwr.js:formatted:1928
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
ChainAnonymousCredentialsProvider @ cwr.js:formatted:1926
e.setAwsCredentials @ cwr.js:formatted:4231
e.initDispatch @ cwr.js:formatted:5485
e @ cwr.js:formatted:5432
e.initCwr @ cwr.js:formatted:5927
(anonymous) @ cwr.js:formatted:5900
(anonymous) @ cwr.js:formatted:5838
(anonymous) @ cwr.js:formatted:5851
(anonymous) @ cwr.js:formatted:5756
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Rn @ cwr.js:formatted:5733
e.init @ cwr.js:formatted:5888
(anonymous) @ cwr.js:formatted:5945
(anonymous) @ cwr.js:formatted:5946
(anonymous) @ cwr.js:formatted:5947
Show 24 more frames
polyfills.cf07b70d8bd3c7d2eb81.js:1 Uncaught (in promise) undefined
invoke @ polyfills.cf07b70d8bd3c7d2eb81.js:1
run @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
scheduleMicroTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
P @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
invokeTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
runTask @ polyfills.cf07b70d8bd3c7d2eb81.js:1
m @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Promise.then (async)
k @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Z @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ cwr.js:formatted:1941
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
(anonymous) @ cwr.js:formatted:1939
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
AnonymousCredentialsProvider @ cwr.js:formatted:1936
(anonymous) @ cwr.js:formatted:1928
(anonymous) @ cwr.js:formatted:1905
(anonymous) @ cwr.js:formatted:1918
(anonymous) @ cwr.js:formatted:1823
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
_ @ cwr.js:formatted:1800
ChainAnonymousCredentialsProvider @ cwr.js:formatted:1926
e.setAwsCredentials @ cwr.js:formatted:4231
e.initDispatch @ cwr.js:formatted:5485
e @ cwr.js:formatted:5432
e.initCwr @ cwr.js:formatted:5927
(anonymous) @ cwr.js:formatted:5900
(anonymous) @ cwr.js:formatted:5838
(anonymous) @ cwr.js:formatted:5851
(anonymous) @ cwr.js:formatted:5756
O @ polyfills.cf07b70d8bd3c7d2eb81.js:1
Rn @ cwr.js:formatted:5733
e.init @ cwr.js:formatted:5888
(anonymous) @ cwr.js:formatted:5945
(anonymous) @ cwr.js:formatted:5946
(anonymous) @ cwr.js:formatted:5947
Show 20 more frames
4polyfills.cf07b70d8bd3c7d2eb81.js:1 Uncaught (in promise) undefined
```

**Comment by qhanam** [comment]
Thanks for bringing this up @asennyey !

Storing the token in a cookie is problematic because of the token's size. It can consume a significant portion of the cookie storage limit for the domain.

How can I reproduce this? When I disable localStorage the errors are [caught and ignored](https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/Authentication.ts#L133).

**Comment by asennyey** [comment]
I just tried to reproduce this in a minimal environment and I wasn't able to replicate the issue, it's probably an issue with our project config. I'll investigate further on our end, but thanks for the feedback on the cookie size.
