### ISSUE TITLE
[General Inquiry]: XMLHttpRequest error

### ISSUE THREAD

**Issue by p-obrien** [aws-observability/aws-rum-web#478]
### What is your general inquiry?

On a busy website I'm receiving thousands of errors reporting events like the below:

Unfortunately the line numbers reported just point at a XMLHttpRequest exception so I'm having trouble understanding what is the cause of this error is or how to avoid it:

```
{
  "event_timestamp": 1701231767000,
  "event_type": "com.amazon.rum.http_event",
  "event_id": "d33e6132-6ea4-4aaa-a63c-7dbcb1549512",
  "event_version": "1.0.0",
  "log_stream": "2023-12-1T12",
  "application_id": “<redacted>",
  "application_version": "1.0.0",
  "metadata": {
    "version": "1.0.0",
    "browserLanguage": "en-US",
    "browserName": "Chrome",
    "browserVersion": "120.0.0.0",
    "osName": "Windows",
    "osVersion": "10",
    "deviceType": "desktop",
    "platformType": "web",
    "pageId": "/go/test”,
    "interaction": "0",
    "title": “Some Page title,
    "domain": "www.mydomain.com”,
    "countryCode": “US”,
    "subdivisionCode": “NY”
  },
  "user_details": {
    "userId": “<redacted>”,
    "sessionId": "<redacted>"
  },
  "event_details": {
    "version": "1.0.0",
    "request": {
      "method": "GET"
    },
    "error": {
      "version": "1.0.0",
      "type": "XMLHttpRequest error",
      "message": "0",
      "stack": "XMLHttpRequest error: 0\n at new t (https://client.rum.us-east-1.amazonaws.com/1.0.2/cwr.js:2:96052)\n    at n.handleXhrErrorEvent (https://client.rum.us-east-1.amazonaws.com/1.0.2/cwr.js:2:97900)"
    }
  }
}
```

**Comment by williazz** [comment]
Hi, v1.0.2 is an extremely old version of the web client and has known issues. Is there a reason you are unable to upgrade? 

As for the error, it looks like there is an error in initializing `new t`, but it's unclear what this object's purpose is because the name has been minified. Have you confirmed that your network conditions are healthy?

I would recommend upgrading before further investigation.

**Comment by williazz** [comment]
v1.0.x should be considered deprecated

**Comment by williazz** [comment]
Closing due to inactivity. Please re-open if you experience issues blocking your upgrade, which would be a high priority action item for us.
